Description: VPC with conditional amazon provided ipv6 cidr block
Parameters:
  Ipv6Pool:
    Description: Amazon provided Ipv6 address pool (1) or bring your own Ipv6 address pool (2)
    Type: Number
    AllowedValues: [1, 2]
Conditions:
  Ipv6PoolIsAmazon: !Equals [ !Ref Ipv6Pool, 1]
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Role
          Value: VPC
  VPCCidrBlockIPv6:
    Type: AWS::EC2::VPCCidrBlock
    Condition: Ipv6PoolIsAmazon
    Properties:
      VpcId: !Ref VPC
      AmazonProvidedIpv6CidrBlock: true
Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
  StackIpv6VPC:
    Description: The Ipv6 cidr block of the vpc
    Value: !If [Ipv6PoolIsAmazon, !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ], 'No value']
    Export:
      Name: !Sub "${AWS::StackName}-VPCIpv6"
